🚧 os icones estao sendo inseridos
lauragabriele/controle-gastos pull request #2
Opened 2023-04-20 17:30 UTC by lauragabriele

2023-04-20 17:41 UTC, jorgebinho commented on src/components/index.js
Arquivo vazio

2023-04-20 17:46 UTC, jorgebinho commented on src/views/Home.vue
Pode utilizar a index da pasta components que está vazia para importar componentes

2023-04-20 17:46 UTC, jorgebinho commented on src/App.vue
>  <style scoped>
Remover CSS não utilizada e se a tag estiver vazia remover ela

2023-04-20 17:48 UTC, jorgebinho commented on src/components/TheHeader.vue
Na linha 11 o color="info" está repetindo em relação ao text-info

2023-04-20 17:49 UTC, jorgebinho commented on src/components/TheHeader.vue
Na linha 21 existe uma tag bg- sem adicionar a cor de backgground

2023-04-20 17:50 UTC, jorgebinho commented on src/components/TheHeader.vue
Na linha 26 o elemento q-icon deve ter autoclose

2023-04-20 17:51 UTC, jorgebinho commented on src/components/TheHeader.vue
>      <div class="q-app" style="min-height: 100vh">
Evitar style in-line

2023-04-20 17:51 UTC, jorgebinho commented on src/components/TheHeader.vue
>            <div></div>
Qual a necessidade dessa linha?

2023-04-20 17:52 UTC, jorgebinho commented on src/components/TheHeader.vue
>                  <q-btn color="red" @click="cancel()"> Cancelar </q-btn>
Pode utilizar o atributo label do q-btn para ele ter autoclose

2023-04-20 17:53 UTC, jorgebinho commented on src/components/TheHeader.vue
> +      <div id="q-app"></div>
um chopp por má identação

2023-04-20 17:54 UTC, jorgebinho commented on src/components/TheHeader.vue
> +              <q-btn dense round flat color="grey" @click="deleteRow(props)" icon="delete"></q-btn>
Elementos sem autoclose

2023-04-20 17:55 UTC, jorgebinho commented on src/components/TheHeader.vue
> +    field: ''
Qual a necessidade da field vazia?

2023-04-20 17:55 UTC, jorgebinho commented on src/components/TheHeader.vue
Existem um CSS com padding

2023-04-20 17:57 UTC, jorgebinho commented on src/views/Home.vue
> +  <the-header />
Componente deve estar escrito em PascalCase

2023-04-24 14:10 UTC, lauragabriele commented on src/components/TheHeader.vue
>      <div class="q-app" style="min-height: 100vh">
ok

2023-04-24 16:39 UTC, julianostroschon requested changes
alguns comentários

2023-04-24 16:39 UTC, julianostroschon commented on src/components/TheHeader.vue
> +      <div class="card bg-white col-3 q-py-md q-px-md">
se há a intenção de aplicar padding em todas as direções, não se faz necessário especificar separado. Ao invés disso, aplicar: `q-pa-md` que aplicará o padding em `all` direções

2023-04-24 16:39 UTC, julianostroschon commented on src/components/TheHeader.vue
> +        <p class="incomeDisplay text-info">
classes devem estar em kebab-case

2023-04-24 16:39 UTC, julianostroschon commented on src/components/TheHeader.vue
> +      <div class="card bg-white col-3 q-py-md q-px-md">
q-pa-md

2023-04-24 16:39 UTC, julianostroschon commented on src/components/TheHeader.vue
> +        <p class="expenseDisplay text-info bg-">
case

2023-04-24 16:39 UTC, julianostroschon commented on src/components/TheHeader.vue
> +          R$ {{ income.toLocaleString("pt-BR", { minimumFractionDigits: 2 }) }}
onde é definido `income` ?

2023-04-24 16:39 UTC, julianostroschon commented on src/components/TheHeader.vue
> +          R$ {{ expense.toLocaleString("pt-BR", { minimumFractionDigits: 2 }) }}
onde é definido `expense`

2023-04-24 16:39 UTC, julianostroschon commented on src/components/TheHeader.vue
> +      <div class="card total col-3 bg-blue-grey-4 q-py-md q-px-md">
q-pa-...

2023-04-24 16:39 UTC, julianostroschon commented on src/components/TheHeader.vue
> +        <p class="totalDisplay text-white">
case

2023-04-24 16:39 UTC, julianostroschon commented on src/components/TheHeader.vue
> +          R$ {{ total.toLocaleString("pt-BR", { minimumFractionDigits: 2 }) }}
declaração

2023-04-24 16:39 UTC, julianostroschon commented on src/components/TheHeader.vue
> +  <div class="app">
class `app`?

2023-04-24 16:39 UTC, julianostroschon commented on src/components/TheHeader.vue
> +    <div class="q-pa-md"></div>
uma div para adicionar um padding, porém vazia?

2023-04-24 16:39 UTC, julianostroschon commented on src/components/TheHeader.vue
> +              <q-btn color="green" @click="save()">Salvar</q-btn>
uma com label e a outra como entre-tags?

2023-04-24 16:39 UTC, julianostroschon commented on src/components/TheHeader.vue
> +    <div class="q-pa-md"></div>
pra quê essas 3 divs?

2023-04-24 16:39 UTC, julianostroschon commented on src/components/TheHeader.vue
> +    <div class="row q-col-gutter-sm"></div>
essa classe pq?

2023-04-24 16:39 UTC, julianostroschon commented on src/components/TheHeader.vue
> +      <template v-slot:body-cell-actions="props">
props?

2023-04-24 17:04 UTC, lauragabriele commented on src/components/TheHeader.vue
> +      <template v-slot:body-cell-actions="props">
para dar o espaçamento entre o botão de novas transações e a tabela de transações

2023-04-24 17:08 UTC, lauragabriele commented on src/components/TheHeader.vue
> +    <div class="row q-col-gutter-sm"></div>
para separar o botao de nova transação da tabela de transações

2023-04-24 17:36 UTC, lauragabriele commented on src/components/TheHeader.vue
> +          R$ {{ income.toLocaleString("pt-BR", { minimumFractionDigits: 2 }) }}
na linha 106 no js

2023-04-24 17:36 UTC, lauragabriele commented on src/components/TheHeader.vue
> +          R$ {{ expense.toLocaleString("pt-BR", { minimumFractionDigits: 2 }) }}
na linha 107 do script

2023-04-24 17:37 UTC, lauragabriele commented on src/components/TheHeader.vue
> +      <template v-slot:body-cell-actions="props">
é o atributo que eu passei para a função de deleção

2023-04-24 17:39 UTC, lauragabriele commented on src/components/TheHeader.vue
> +    <div class="q-pa-md"></div>
serve para espaçar o botão de nova transação e a tabela de transações

2023-04-24 17:42 UTC, lauragabriele commented on src/components/TheHeader.vue
> +    <div class="q-pa-md"></div>
ajustei o botão de transação para dentro da div

2023-04-24 18:05 UTC, lauragabriele commented on src/components/TheHeader.vue
> +          R$ {{ total.toLocaleString("pt-BR", { minimumFractionDigits: 2 }) }}
declarado na linha 109 do script

2024-11-06 19:45 UTC, merged